# -*- coding: utf-8 -*-
"""iphone_16_manual_scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvyOAyx2_1FcuzuSR47vF7yKgUv0sSLj
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
!pip install PyPDF2

import os
import json
from PyPDF2 import PdfReader
import time

# Set up the file path for the PDF manual
pdf_path = '/content/drive/My Drive/Colab Notebooks/rita/docextract/iphone_16_manual.pdf'
output_file = '/content/drive/My Drive/Colab Notebooks/rita/docextract/iphone_16_manual_extracted.json'

# Initialize the output list
extracted_data = []

# Function to extract text from each page of the PDF
def extract_pdf_content(pdf_path, device_name="iPhone 16"):
    try:
        # Open the PDF file
        reader = PdfReader(pdf_path)
        total_pages = len(reader.pages)
        print(f"Total pages in PDF: {total_pages}")

        # Iterate through each page
        for page_number in range(total_pages):
            page = reader.pages[page_number]
            text = page.extract_text()

            # Show progress
            print(f"Extracting content from page {page_number + 1}/{total_pages}...")

            # Store the content in the required format
            if text:
                extracted_data.append({
                    "text": text,
                    "page": page_number + 1,
                    "device": device_name
                })

            # Optional: Delay to simulate progress (can be removed if not needed)
            time.sleep(0.5)

        print("PDF extraction completed.")
    except Exception as e:
        print(f"Error extracting content from PDF: {str(e)}")

# Extract content from the PDF
extract_pdf_content(pdf_path)

# Save the extracted data to a JSON file
if extracted_data:
    try:
        with open(output_file, 'w', encoding='utf-8') as file:
            json.dump(extracted_data, file, ensure_ascii=False, indent=2)
        print(f"Data successfully saved to '{output_file}'.")
    except Exception as e:
        print(f"Error saving data to JSON file: {str(e)}")
else:
    print("No data extracted from the PDF.")

# Download the JSON file to your local device (specific to Google Colab)
from google.colab import files
files.download(output_file)